FROM ubuntu:14.04
MAINTAINER "Marti Martinez" <martinezah@gmail.com>

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python python-pip python-dev

ENTRYPOINT ["/bin/bash"]
CMD ["-l"]
